### ISSUE TITLE
Few minor UI issues

### ISSUE THREAD

**Issue by harshilpradhan-simformsolutions** [ashishkk22/web-app-in-js#2]
This is the navbar from actual webpage
![image](https://user-images.githubusercontent.com/75989919/219962926-77af861c-1af2-4e39-8f72-0df98d0e9776.png)

We can see it has more space between logo (name in bold) and nav links.

Additionally, navbar has border bottom instead of shadow.

**Comment by ashishkk22** [comment]
added the space between logo and nav links.
yes navbar has border bottom but when top is near so i have added the shadow and border bottom based on the scroll position.
